# Generated by Django 5.0.4 on 2024-04-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userinfo_email_userinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='balance',
            field=models.FloatField(blank=True, null=True, verbose_name='余额'),
        ),
    ]
