# Generated by Django 5.0.4 on 2024-04-18 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userinfo_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, '微博明星'), (2, '微博媒体'), (3, '微博新闻')], verbose_name='分类')),
                ('OrderNumber', models.CharField(max_length=32, verbose_name='订单号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='订单费用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='用户')),
            ],
        ),
    ]
