# Generated by Django 5.0.4 on 2024-04-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='采集数量'),
        ),
    ]
