# Generated by Django 5.0.4 on 2024-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='余额'),
        ),
    ]
