# Generated by Django 5.0.4 on 2024-04-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userinfo_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weibo_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='微博id'),
        ),
    ]
